import { test, expect } from "@playwright/test";
import * as fs from "fs";
import * as path from "path";

/**
 * WebGPU Activation Matching Test — Phase 6 skeleton.
 *
 * Compares WebGPU intermediate activations against reference .npy files
 * generated by dump_activations.py (Phase 3).
 *
 * Adapt this skeleton:
 *   1. Update MODEL_URL and ACTIVATION_DIR paths
 *   2. Update the loadModel / runInference calls to match your API
 *   3. Add checkpoint names matching your .npy filenames
 */

const MODEL_URL = "http://localhost:3000/models/";
const ACTIVATION_DIR = path.resolve("models/activations");

// Tolerance levels — tighten as bugs are fixed
const TOLERANCES = {
  f32: { atol: 0.01, rtol: 0.01 },
  f16: { atol: 0.1, rtol: 0.05 },
};

/**
 * Parse a .npy file into a Float32Array + shape.
 * Supports float32 and float64 .npy files (v1.0 format).
 */
function parseNpy(buffer: Buffer): { data: Float32Array; shape: number[] } {
  // .npy format: 6-byte magic, 2-byte version, 2-byte header length, ASCII header
  const headerLen = buffer.readUInt16LE(8);
  const header = buffer.subarray(10, 10 + headerLen).toString("ascii");

  // Parse shape from header: {'descr': '<f4', 'fortran_order': False, 'shape': (1, 256), }
  const shapeMatch = header.match(/shape':\s*\(([^)]*)\)/);
  if (!shapeMatch) throw new Error(`Cannot parse .npy header: ${header}`);

  const shape = shapeMatch[1]
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
    .map(Number);

  const descrMatch = header.match(/descr':\s*'([^']+)'/);
  const descr = descrMatch ? descrMatch[1] : "<f4";

  const dataOffset = 10 + headerLen;
  const rawData = buffer.subarray(dataOffset);

  let data: Float32Array;
  if (descr === "<f4" || descr === "float32") {
    data = new Float32Array(rawData.buffer, rawData.byteOffset, rawData.byteLength / 4);
  } else if (descr === "<f8" || descr === "float64") {
    const f64 = new Float64Array(rawData.buffer, rawData.byteOffset, rawData.byteLength / 8);
    data = new Float32Array(f64);
  } else {
    throw new Error(`Unsupported .npy dtype: ${descr}`);
  }

  return { data, shape };
}

/**
 * Compare two Float32Arrays with allclose tolerance:
 *   |a - b| <= atol + rtol * |b|
 */
function allclose(
  actual: Float32Array,
  expected: Float32Array,
  atol: number,
  rtol: number
): { pass: boolean; maxErr: number; meanErr: number; nanCount: number } {
  if (actual.length !== expected.length) {
    return { pass: false, maxErr: Infinity, meanErr: Infinity, nanCount: 0 };
  }

  let maxErr = 0;
  let sumErr = 0;
  let nanCount = 0;

  for (let i = 0; i < actual.length; i++) {
    if (isNaN(actual[i])) {
      nanCount++;
      continue;
    }
    const err = Math.abs(actual[i] - expected[i]);
    const tol = atol + rtol * Math.abs(expected[i]);
    maxErr = Math.max(maxErr, err);
    sumErr += err;
  }

  const meanErr = sumErr / (actual.length - nanCount || 1);
  const pass = maxErr <= atol + rtol * maxErr && nanCount === 0;

  return { pass, maxErr, meanErr, nanCount };
}

// ============================================================================
// Test
// ============================================================================

test("activation matching — all checkpoints", async ({ page }) => {
  // Navigate to test page that exposes the model API
  await page.goto("http://localhost:3000/");

  // Wait for WebGPU to be available
  const hasWebGPU = await page.evaluate(() => !!navigator.gpu);
  expect(hasWebGPU).toBe(true);

  // Load model with debug capture enabled
  // TODO: Adapt this to your model's API
  const activations = await page.evaluate(async (modelUrl) => {
    // @ts-expect-error — loadModel is exposed by the test page
    const model = await loadModel(modelUrl, { debugCapture: true });

    // TODO: Use the EXACT same input as dump_activations.py (same seed, same values)
    // @ts-expect-error — runInference is exposed by the test page
    const result = await model.runInference(/* test input here */);

    // Collect debug activations as plain arrays for transfer back to Node
    const captured: Record<string, { data: number[]; shape: number[] }> = {};
    // @ts-expect-error — debugActivations is a Map<string, Float32Array>
    for (const [name, arr] of model.debugActivations.entries()) {
      captured[name] = {
        data: Array.from(arr),
        shape: [], // TODO: populate with actual shape
      };
    }
    return captured;
  }, MODEL_URL);

  // Compare each checkpoint against reference .npy
  const npyFiles = fs
    .readdirSync(ACTIVATION_DIR)
    .filter((f) => f.endsWith(".npy"))
    .sort();

  const tol = TOLERANCES.f32;
  const results: Array<{
    name: string;
    pass: boolean;
    maxErr: number;
    meanErr: number;
    nanCount: number;
  }> = [];

  for (const npyFile of npyFiles) {
    const checkpointName = npyFile.replace(/^\d+_/, "").replace(".npy", "");

    // Skip input files
    if (npyFile.startsWith("000_input_")) continue;

    const refBuf = fs.readFileSync(path.join(ACTIVATION_DIR, npyFile));
    const ref = parseNpy(refBuf);

    const actual = activations[checkpointName];
    if (!actual) {
      results.push({
        name: checkpointName,
        pass: false,
        maxErr: Infinity,
        meanErr: Infinity,
        nanCount: 0,
      });
      continue;
    }

    const actualArr = new Float32Array(actual.data);
    const comparison = allclose(actualArr, ref.data, tol.atol, tol.rtol);

    results.push({ name: checkpointName, ...comparison });
  }

  // Report
  console.log("\n=== Activation Matching Report ===\n");
  let allPassed = true;
  for (const r of results) {
    const status = r.pass ? "PASS" : "FAIL";
    const nanStr = r.nanCount > 0 ? ` (${r.nanCount} NaN!)` : "";
    console.log(
      `  [${status}] ${r.name}: maxErr=${r.maxErr.toFixed(6)}, meanErr=${r.meanErr.toFixed(6)}${nanStr}`
    );
    if (!r.pass) allPassed = false;
  }
  console.log(`\n${results.filter((r) => r.pass).length}/${results.length} checkpoints passed\n`);

  expect(allPassed).toBe(true);
});
